name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Detailed Output
        run: ./gradlew build --info

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew :android:assembleDebug

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: android/build/outputs/apk/debug/


