name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle


    - name: Setup NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
        unzip -qq android-ndk-r21d-linux-x86_64.zip
        export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21d
        echo "export ANDROID_NDK_HOME=${ANDROID_NDK_HOME}" >> $GITHUB_ENV
      shell: bash


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
