name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup NDK
      id: setup-ndk
      run: |
        if [ ! -d "$ANDROID_NDK_HOME" ]; then
          wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
          unzip -qq android-ndk-r21d-linux-x86_64.zip
          export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21d
          echo "export ANDROID_NDK_HOME=${ANDROID_NDK_HOME}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Cache NDK
      uses: actions/cache@v2
      with:
        path: ${{ steps.setup-ndk.outputs.ANDROID_NDK_HOME }}
        key: ndk-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
